# This is a basic workflow to help you get started with Actions

name: CI

env:
  SMVERSION: 1.11
  SMPACKAGE_URL_PREFIX: "http://sourcemod.net/latest.php?os=linux&version="

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Reset score
        uses: actions/checkout@v3
        with:
          path: csgo_reset_score
      
      - name: Checkout smlib
        uses: actions/checkout@v3
        with:
          repository: bcserv/smlib
          fetch-depth: 1
          path: smlib

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -L "$SMPACKAGE_URL_PREFIX${SMVERSION}" --output sourcemod.tar.gz
          tar xfz sourcemod.tar.gz
          cp smlib/scripting/include/* addons/sourcemod/scripting/include -r
          cp csgo_reset_score/*.sp addons/sourcemod/scripting/ -r
          cd addons/sourcemod/scripting
          chmod +x spcomp
          chmod +x spcomp64
          chmod +x compile.sh
          ./compile.sh reset-score.sp
